### PR TITLE
Port demo to Godot 3.

### PR DESCRIPTION
**Pull request by rcorre**

### CODE REVIEW

**Comment by empyreanx** [comment]
Sorry it's taken so long for a response. I've been writing my own 2D engine so Godot hasn't been on my radar. I'll look this over tomorrow and get it merged into master. I'll leave a branch with old Godot 2 code in it for posterity.

**Comment by rcorre** [comment]
No worries, thanks for posting this demo, it was very helpful!

**Comment by empyreanx** [comment]
I'm having difficulty getting it to run. The latest error is,
`Cannot use subscript operator on a base of type "null"`

This occurs a number of times. This is the first instance:
`var pos = lerp_pos(transform.get_origin(), state[0], 1.0 - ALPHA)`

**Comment by empyreanx** [comment]
I was using the master branch. I'll try it against one of the release branches

**Comment by empyreanx** [comment]
I managed to get it working. Thanks for the PR!

**Comment by rcorre** [comment]
> I was using the master branch. I'll try it against one of the release branches

Yep, that makes sense. `master` is 4.0 now

**Pull request merged**
